language: python
python:
  - "2.7"
  - "3.4"
before_install:
    - locate libtdsodbc.so
    - if [ "$DB" = "azure" ] ; then mkdir /tmp/azure; fi
    - if [ "$DB" = "azure" ] ; then openssl aes-256-cbc -K $encrypted_d6387f57280a_key -iv $encrypted_d6387f57280a_iv -in travis-ci/azure.tar.enc -out /tmp/azure/azure.tar -d; fi
    - if [ "$DB" = "azure" ] ; then tar xvf /tmp/azure/azure.tar -C /tmp/azure/; fi
    - if [ "$DB" = "azure" ] ; then source travis-ci/start_sql_azure.sh ; fi
install: pip install -r requirements.txt
before_script:
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create database sqlshare_app'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create user "sqlshare_user" identified by "ss_pass"'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'grant all on *.* to sqlshare_user'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'grant grant option on *.* to sqlshare_user'; fi
  - sudo apt-get install unixODBC-dev
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install PyMySQL
  - pip install django_pyodbc
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
env:
  matrix:
#    - DB=sqlite3
#    - DB=mysql
    - DB=azure
  global:
    - SUBSCRIPTION_ID=af6a4ccb-f42b-4319-b0c0-10b51fcdebee
    - secure: "cQJu68nqqjlYMxTTp5KnBjUcMFamAqi2A8eVvsabZXYwNHL+Ay+2+NEUZTPsTOISY1CrXRp7xilvUCj1jlBQwcrhjPs5nMN/u3IHafOja7k14nMAjCKURts6MklGshetAp19rVxWy0pSkJvofADFfy5l9ps0mhvNO4HTnmr0sqs="
script:
  - pep8 sqlshare_rest/ --exclude=migrations,sqlshare_rest/tests.py,sqlshare_rest/test/
  - coverage run --source=sqlshare_rest/ --omit=sqlshare_rest/migrations/* manage.py test sqlshare_rest
after_script:
  - coveralls
  - if [ "$DB" = "azure" ] ; then source travis-ci/stop_sql_azure.sh ; fi
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
