# from https://raw.githubusercontent.com/joke2k/django-environ/master/appveyor.yml
build: false
environment:
  PYTHONIOENCODING: "utf-8"
  matrix:
    - PYTHON: "C:/Python27"
      DB: "sqlite3"
    - PYTHON: "C:/Python34"
      DB: "sqlite3"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install coverage"
# No coveralls for windows - "ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support."
#  - "%PYTHON%/Scripts/pip.exe install python-coveralls"
  - "%PYTHON%/Scripts/pip.exe install pep8"
  - "%PYTHON%/Scripts/pip.exe install PyMySQL"
  - "ls"
  - "copy travis-ci/manage.py manage.py"
test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe manage.py test sqlshare_rest"
  - "%PYTHON%/Scripts/pep8 sqlshare_rest/ --exclude=migrations,sqlshare_rest/tests.py,sqlshare_rest/test/"
