# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlshare_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='backend_terminate_data',
            field=models.TextField(null=True),
        ),
    ]
