from sqlshare_rest.test.parser import TestParser
from sqlshare_rest.test.db_utils import TestBackendSettings
from sqlshare_rest.test.backend.mysql import TestMySQLBackend
from sqlshare_rest.test.backend.sqlite3 import TestSQLite3Backend
from sqlshare_rest.test.dao.dataset import TestDatasetDAO
from sqlshare_rest.test.api.dataset import DatsetAPITest
from sqlshare_rest.test.api.dataset_list import DatsetListAPITest
from sqlshare_rest.test.api.permissions import DatasetPermissionsAPITest
#from sqlshare_rest.test.api.dataset_tags import DatasetTagsAPITest
#from sqlshare_rest.test.api.file_parser import FileParserAPITest
#from sqlshare_rest.test.api.file_upload import FileUploadAPITest
#from sqlshare_rest.test.api.query import QueryAPITest
#from sqlshare_rest.test.api.query_list import QueryListAPITest
